name: Build Windows EXE

on:
  workflow_dispatch:   # run manually
  push:
    paths:
      - 'build_json_gui.py'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify repository root contents
        run: |
          echo "Listing repository root..."
          dir
          if not exist build_json_gui.py (
            echo [ERROR] build_json_gui.py not found at repo root. >&2
            exit /b 1
          )

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # <- Pin to 3.11 for PyInstaller compatibility

      - name: Show Python & pip versions
        run: |
          python --version
          python -m pip --version

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pyinstaller
          python -m PyInstaller --version

      - name: Build EXE (windowed, onefile)
        shell: cmd
        run: |
          echo Building EXE...
          python -m PyInstaller --clean --noconfirm --onefile --windowed build_json_gui.py
          echo Listing dist folder...
          if exist dist (
            dir dist
          ) else (
            echo [ERROR] dist folder not found. Build likely failed. >&2
            exit /b 1
          )
          if not exist dist\build_json_gui.exe (
            echo [ERROR] build_json_gui.exe not found in dist. >&2
            exit /b 1
          )

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: build_json_gui-exe
          path: dist/build_json_gui.exe
          if-no-files-found: error

      # If anything fails above, capture logs for quick diagnosis
      - name: Upload build logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-logs
          path: |
            build/**
            dist/**
            *.spec
            *.log
