name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    paths:
      - 'build_json_gui.py'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify repository root contents (PowerShell)
        run: |
          Write-Host "Listing repository root..."
          Get-ChildItem -Force
          if (!(Test-Path -Path "build_json_gui.py")) {
            Write-Error "[ERROR] build_json_gui.py not found at repo root."
            exit 1
          }

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python & pip versions
        run: |
          python --version
          python -m pip --version

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pyinstaller
          python -m PyInstaller --version

      - name: Build EXE (windowed, onefile)
        run: |
          Write-Host "Building EXE..."
          python -m PyInstaller --clean --noconfirm --onefile --windowed build_json_gui.py
          Write-Host "Listing dist folder..."
          if (!(Test-Path -Path "dist")) {
            Write-Error "[ERROR] dist folder not found. Build likely failed."
            exit 1
          }
          Get-ChildItem dist -Force
          if (!(Test-Path -Path "dist/build_json_gui.exe")) {
            Write-Error "[ERROR] build_json_gui.exe not found in dist."
            exit 1
          }

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: build_json_gui-exe
          path: dist/build_json_gui.exe
          if-no-files-found: error

      - name: Upload build logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-logs
          path: |
            build/**
            dist/**
            *.spec
            *.log
