name: Build Windows EXE (Self-Writing Script)

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python & pip
        shell: pwsh
        run: |
          python --version
          python -m pip --version

      - name: Install PyInstaller
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pyinstaller
          python -m PyInstaller --version

      - name: Write clean build_json_gui.py (from here-string)
        shell: pwsh
        run: |
          @'
# build_json_gui.py
import json, csv, copy, tkinter as tk
from tkinter import filedialog, messagebox, ttk
from typing import Any, Dict, List, Tuple

USER_NAME = "KimKwang"

def read_json(path: str):
    with open(path, "r", encoding="utf-8") as f:
        return json.loads(f.read().strip())

def write_json(path: str, data: Any):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

def read_csv(path: str) -> List[Dict[str,str]]:
    rows = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        for r in csv.DictReader(f):
            rows.append({(k or "").strip(): (v or "").strip() for k, v in r.items()})
    return rows

def deep_clone(obj: Any) -> Any:
    return copy.deepcopy(obj)

class TemplateForms:
    def __init__(self, template_obj: Any):
        if isinstance(template_obj, list): root = template_obj[0]
        elif isinstance(template_obj, dict): root = template_obj
        else: raise ValueError("Unexpected template format")
        ds_dict = root.get("data_sets", {}) or {}
        if not ds_dict: raise ValueError("Template does not contain data_sets")
        first_ds_key = next(iter(ds_dict.keys()))
        self.extraction_proto = deep_clone(ds_dict[first_ds_key])

        self.spd_proto = None
        self.safety_proto = None
        self.perf_discrete_proto = None
        self.harms_proto = None
        self.followup_proto = None

        for _, v in (self.extraction_proto.get("child_forms", {}) or {}).items():
            name = (v.get("form") or "").strip()
            if name == "Study Parameters and Demographics": self.spd_proto = deep_clone(v)
            elif name == "Safety": self.safety_proto = deep_clone(v)
            elif name == "Performance (discrete)": self.perf_discrete_proto = deep_clone(v)
            elif name == "Follow-up Subform": self.followup_proto = deep_clone(v)

        if self.spd_proto:
            for _, v in (self.spd_proto.get("child_forms", {}) or {}).items():
                if (v.get("form") or "").strip() == "Follow-up Subform" and self.followup_proto is None:
                    self.followup_proto = deep_clone(v)

        if self.safety_proto:
            for _, v in (self.safety_proto.get("child_forms", {}) or {}).items():
                if (v.get("form") or "").strip() == "Harms":
                    self.harms_proto = deep_clone(v)
                    break

    def question_types(self, form_proto: Dict[str, Any]) -> Dict[str, str]:
        out = {}
        for q in form_proto.get("data", []) or []:
            out[q.get("question","")] = q.get("type","Text")
        return out

class JSONBuilder:
    def __init__(self, tf: TemplateForms):
        self.t = tf
        self.next_id = 10000

    def _gen_id(self) -> str:
        self.next_id += 1
        return str(self.next_id)

    def _make_extraction(self, refid: str) -> Dict[str, Any]:
        ds = deep_clone(self.t.extraction_proto)
        ds["key"] = str(refid)
        ds["user"] = USER_NAME
        for q in ds.get("data", []) or []:
            if q.get("question") == "Article Identifier":
                r = q.setdefault("response", {})
                r["text"] = str(refid)
        ds["child_forms"] = {}
        return ds

    def _populate_form_from_row(self, form_proto: Dict[str, Any], row: Dict[str, str]) -> Dict[str, Any]:
        form = deep_clone(form_proto)
        form["user"] = USER_NAME
        form["data"] = []
        qtypes = self.t.question_types(form_proto)
        for q_text, q_type in qtypes.items():
            if q_text in row:
                val = row[q_text]
                if q_text == "Associated CERs":
                    items = [x.strip() for x in val.replace(";", ",").split(",") if x.strip()]
                    if not items:
                        form["data"].append({"question": q_text, "type": q_type, "response": {"text": "", "answer": ""}})
                    else:
                        for item in items:
                            form["data"].append({"question": q_text, "type": q_type, "response": {"text": "", "answer": item}})
                else:
                    resp = {"answer":"", "text":""}
                    if q_type in ("Radio","Checkbox"): resp["answer"] = val
                    else: resp["text"] = val
                    form["data"].append({"question": q_text, "type": q_type, "response": resp})
            else:
                form["data"].append({"question": q_text, "type": q_type, "response": {"answer": "", "text": ""}})
        if "child_forms" not in form: form["child_forms"] = {}
        return form

    def build(self,
              template_root: Dict[str, Any],
              spd_rows: List[Dict[str, str]],
              safety_rows: List[Dict[str, str]],
              perf_rows: List[Dict[str, str]],
              harms_rows: List[Dict[str, str]],
              followup_rows: List[Dict[str, str]] = None) -> List[Dict[str, Any]]:
        followup_rows = followup_rows or []

        spd_by_refid: Dict[str, List[Dict[str, str]]] = {}
        for r in spd_rows:
            rf = (r.get("refid") or "").strip()
            if rf: spd_by_refid.setdefault(rf, []).append(r)

        safety_by_key: Dict[Tuple[str, str], List[Dict[str, str]]] = {}
        for r in safety_rows:
            rf = (r.get("refid") or "").strip()
            spd = (r.get("spd_id") or "").strip()
            safety_by_key.setdefault((rf, spd), []).append(r)

        harms_by_safety_id: Dict[str, List[Dict[str, str]]] = {}
        for r in harms_rows:
            sid = (r.get("safety_id") or "").strip()
            if sid: harms_by_safety_id.setdefault(sid, []).append(r)

        perf_by_key: Dict[Tuple[str, str], List[Dict[str, str]]] = {}
        for r in perf_rows:
            rf = (r.get("refid") or "").strip()
            spd = (r.get("spd_id") or "").strip()
            perf_by_key.setdefault((rf, spd), []).append(r)

        followup_by_key: Dict[Tuple[str, str], List[Dict[str, str]]] = {}
        for r in followup_rows:
            rf = (r.get("refid") or "").strip()
            spd = (r.get("spd_id") or "").strip()
            followup_by_key.setdefault((rf, spd), []).append(r)

        out: List[Dict[str, Any]] = []
        for refid, spd_list in spd_by_refid.items():
            root = {"refid": int(refid) if refid.isdigit() else refid,
                    "tags": [], "attachments": [], "biblio_string": "", "data_sets": {}}
            ds_id = self._gen_id()
            extraction = self._make_extraction(refid)
            extraction["child_forms"] = {}

            for spd_row in spd_list:
                spd_id = (spd_row.get("spd_id") or "").strip()
                if not spd_id: continue
                if self.t.spd_proto is None:
                    raise ValueError("Template missing SP&D prototype.")
                spd_form = self._populate_form_from_row(self.t.spd_proto, spd_row)
                spd_form["key"] = f"spd_{spd_id}"
                spd_form["form"] = "Study Parameters and Demographics"
                spd_form["user"] = USER_NAME
                spd_form["child_forms"] = {}

                extraction["child_forms"][f"spd_{spd_id}"] = spd_form

                for perf_row in perf_by_key.get((refid, spd_id), []):
                    if self.t.perf_discrete_proto is None: continue
                    perf_form = self._populate_form_from_row(self.t.perf_discrete_proto, perf_row)
                    perf_form["key"] = f"perf_{self._gen_id()}"
                    perf_form["form"] = "Performance (discrete)"
                    perf_form["user"] = USER_NAME
                    spd_form["child_forms"][self._gen_id()] = perf_form

                for srow in safety_by_key.get((refid, spd_id), []):
                    if self.t.safety_proto is None: continue
                    safety_form = self._populate_form_from_row(self.t.safety_proto, srow)
                    safety_id = (srow.get("safety_id") or "").strip()
                    safety_form["key"] = f"safety_{safety_id or self._gen_id()}"
                    safety_form["form"] = "Safety"
                    safety_form["user"] = USER_NAME
                    safety_form["child_forms"] = {}
                    for hrow in harms_by_safety_id.get(safety_id, []):
                        if self.t.harms_proto is None: continue
                        harms_form = self._populate_form_from_row(self.t.harms_proto, hrow)
                        harms_form["key"] = f"harms_{self._gen_id()}"
                        harms_form["form"] = "Harms"
                        harms_form["user"] = USER_NAME
                        safety_form["child_forms"][self._gen_id()] = harms_form
                    spd_form["child_forms"][self._gen_id()] = safety_form

                for fu_row in followup_by_key.get((refid, spd_id), []):
                    if self.t.followup_proto is not None:
                        fu_form = self._populate_form_from_row(self.t.followup_proto, fu_row)
                        fu_form["form"] = "Follow-up Subform"
                        fu_form["key"] = fu_form.get("key", f"followup_{self._gen_id()}")
                       
