name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    paths:
      - 'build_json_gui.py'
      - '.github/workflows/build.yml'
      - 'requirements.txt'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas pyinstaller
          fi
          python -c "import sys; print('Python:', sys.version)"
          python -m pip --version
          pyinstaller --version

      - name: Preflight syntax check
        shell: bash
        run: python -m py_compile build_json_gui.py

      - name: Build EXE (windowed, onefile)
        shell: bash
        run: |
          pyinstaller --clean --noconfirm --onefile --windowed build_json_gui.py
          ls -la dist || true

      - name: Verify artifact exists
        shell: bash
        run: test -f dist/build_json_gui.exe

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: build_json_gui-exe
          path: dist/build_json_gui.exe
          if-no-files-found: error
