name: Build JSON GUI EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'   # optional: speeds up pip installs
          # DO NOT set: pip-install: true

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          } else {
            # Minimal deps for this app
            pip install pandas
          }
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --name json-builder `
            app/json_builder_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: json-builder-exe
          path: dist/json-builder.exe
