name: Build Windows EXE

on:
  workflow_dispatch:  # lets you run it manually
  push:
    paths:
      - 'build_json_gui.py'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build EXE (windowed)
        run: |
          py -m PyInstaller --clean --onefile --windowed build_json_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_json_gui-exe
          path: dist/build_json_gui.exe
