name: Minimal Heredoc Sanity Check

on:
  workflow_dispatch:

jobs:
  just-write-file:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write Python via bash heredoc
        shell: bash
        run: |
          set -e
          mkdir -p app
          cat > app/build_json_gui.py <<'PY'
# build_json_gui.py
# JSON builder GUI for DistillerSR-like template
# - SP&D under Extraction.child_forms keyed as "spd_XX"
# - Safety under SP&D; Harms under Safety linked by safety_id
# - Performance (discrete) under SP&D
# - Optional Follow-up Subform
# - user = "KimKwang" everywhere
import json, csv, copy, tkinter as tk
from tkinter import filedialog, messagebox, ttk
from typing import Any, Dict, List, Tuple, Set
from collections import defaultdict
print("Sanity check: file was written and Python starts OK.")
PY

      - name: Show first 20 lines
        shell: bash
        run: sed -n '1,20p' app/build_json_gui.py
