name: Build JSON GUI EXE

on:
  workflow_dispatch:        # allow manual runs from the Actions tab
  push:
    branches: [ main ]      # build automatically on pushes to main

jobs:
  build-windows:
    runs-on: windows-latest   # build on Windows for a Windows .exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'         # speeds up dependency installs
      # setup-python is the GitHub-recommended way to install Python on runners.
      # https://github.com/marketplace/actions/setup-python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile `
            --name json-builder `
            app/json_builder_gui.py
      # PyInstaller --onefile bundles everything into a single executable.
      # PyInstaller is not a cross-compiler; build on the target OS.
      # https://pyinstaller.org/en/stable/usage.html
      # https://pyinstaller.org/en/stable/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: json-builder-exe
          path: dist/json-builder.exe
